#!/bin/bash
#
# download-agent-data.sh - Sync agent-generated data from server to local agent_data folder
#
# This script efficiently downloads all data generated by the AI agent on the server
# to the local agent_data/ folder using rsync, avoiding re-downloads of unchanged files.
#
# Features:
# - Incremental sync (only transfers changed files)
# - Checksum-based comparison (prevents partial file syncs)
# - Post-sync integrity verification (detects & fixes size mismatches)
# - Excludes temporary files (*.tmp, *.lock)
# - Preserves file permissions and timestamps
# - Dry-run mode to preview changes
# - Force mode for full resync
#
# Usage:
#   ./download-agent-data.sh              # Incremental sync (recommended)
#   ./download-agent-data.sh --dry-run    # Preview what would be synced
#   ./download-agent-data.sh --force      # Full sync (transfers all files)
#   ./download-agent-data.sh --help       # Show help
#

set -e

SERVER="debian"
REMOTE_DIR="~/ai_home"
LOCAL_DIR="./agent_data"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[!!]${NC} $1"; }
log_error() { echo -e "${RED}[ERR]${NC} $1"; }
log_step() { echo -e "\n${BLUE}==>${NC} $1"; }
log_file() { echo -e "   ${BLUE}--${NC} $1"; }

# Parse arguments
DRY_RUN=false
FORCE=false

for arg in "$@"; do
    case $arg in
        --dry-run)
            DRY_RUN=true
            ;;
        --force)
            FORCE=true
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --dry-run    Show what would be synced without actually doing it"
            echo "  --force      Force full sync (ignore timestamps)"
            echo "  --help       Show this help"
            echo ""
            echo "This script syncs agent data from server ($SERVER:$REMOTE_DIR)"
            echo "to local folder ($LOCAL_DIR) using rsync for efficiency."
            exit 0
            ;;
    esac
done

echo "========================================"
echo "   Agent Data Sync Script"
echo "========================================"
echo ""

# Check SSH connectivity
log_step "Checking server connectivity..."
if ! ssh -o ConnectTimeout=5 "$SERVER" "echo 'OK'" > /dev/null 2>&1; then
    log_error "Cannot connect to server '$SERVER'"
    echo "Make sure the server is running and SSH is configured."
    exit 1
fi
log_info "Connected to $SERVER"

# Create local directory if it doesn't exist
log_step "Ensuring local directory exists..."
mkdir -p "$LOCAL_DIR"
log_info "Local directory ready: $LOCAL_DIR"

# Build rsync options
# Use --checksum instead of timestamp-only comparison to prevent partial file syncs.
# This catches cases where a file was still being written during a previous rsync,
# leaving a truncated local copy that rsync would otherwise skip (same mtime).
RSYNC_OPTS="-avz --delete --checksum"
RSYNC_OPTS="$RSYNC_OPTS --exclude='.git/'"
RSYNC_OPTS="$RSYNC_OPTS --exclude='*.tmp'"
RSYNC_OPTS="$RSYNC_OPTS --exclude='*.lock'"
RSYNC_OPTS="$RSYNC_OPTS --exclude='.last_sync'"

if [ "$DRY_RUN" = true ]; then
    RSYNC_OPTS="$RSYNC_OPTS --dry-run"
    echo ""
    log_warn "DRY RUN MODE - No files will be actually transferred"
fi

if [ "$FORCE" = true ]; then
    RSYNC_OPTS="$RSYNC_OPTS --ignore-times"
    log_warn "FORCE MODE - Ignoring timestamps, full sync"
fi

# Show what we're doing
echo ""
echo "Sync Configuration:"
echo "  From: $SERVER:$REMOTE_DIR/"
echo "  To:   $LOCAL_DIR/"
echo "  Mode: $([ "$DRY_RUN" = true ] && echo 'DRY RUN' || echo 'LIVE')"
echo ""

# Perform the sync
log_step "Starting rsync sync..."

RSYNC_OPTS="$RSYNC_OPTS --itemize-changes"

# Capture rsync output
RSYNC_OUTPUT=$(rsync $RSYNC_OPTS -e ssh "$SERVER:$REMOTE_DIR/" "$LOCAL_DIR/" 2>&1)
RSYNC_EXIT=$?

# Parse output to find actually transferred files
TRANSFERRED_FILES=$(echo "$RSYNC_OUTPUT" | grep -E "^>f|^\*deleting" | grep -v "^>f\.\.\.\.\.\.\.\.\.\.\." || true)
if [ -n "$TRANSFERRED_FILES" ]; then
    TRANSFERRED_COUNT=$(echo "$TRANSFERRED_FILES" | wc -l)
else
    TRANSFERRED_COUNT=0
fi

# Show what happened
if [ "$DRY_RUN" = true ]; then
    echo "Files that would be synced:"
    echo "----------------------------------------"
    if [ "$TRANSFERRED_COUNT" -gt 0 ] && [ -n "$TRANSFERRED_FILES" ]; then
        echo "$TRANSFERRED_FILES" | head -20 | while read -r line; do
            filename=$(echo "$line" | sed 's/^[^ ]* //')
            if echo "$line" | grep -q "^\*deleting"; then
                echo -e "   ${RED}DEL${NC}  $filename"
            elif echo "$line" | grep -q "^>f+++"; then
                echo -e "   ${GREEN}NEW${NC}  $filename"
            else
                echo -e "   ${YELLOW}UPD${NC}  $filename"
            fi
        done
        if [ "$TRANSFERRED_COUNT" -gt 20 ]; then
            echo "   ... and $(($TRANSFERRED_COUNT - 20)) more files"
        fi
        echo ""
        log_info "$TRANSFERRED_COUNT file(s) would be transferred"
    else
        log_info "All files are up to date - nothing to transfer"
    fi
else
    echo "Transferred files:"
    echo "----------------------------------------"
    if [ "$TRANSFERRED_COUNT" -gt 0 ] && [ -n "$TRANSFERRED_FILES" ]; then
        echo "$TRANSFERRED_FILES" | head -20 | while read -r line; do
            filename=$(echo "$line" | sed 's/^[^ ]* //')
            if echo "$line" | grep -q "^\*deleting"; then
                echo -e "   ${RED}DEL${NC}  $filename"
            elif echo "$line" | grep -q "^>f+++"; then
                echo -e "   ${GREEN}NEW${NC}  $filename"
            else
                echo -e "   ${YELLOW}UPD${NC}  $filename"
            fi
        done
        if [ "$TRANSFERRED_COUNT" -gt 20 ]; then
            echo "   ... and $(($TRANSFERRED_COUNT - 20)) more files"
        fi
        echo ""
        log_info "$TRANSFERRED_COUNT file(s) transferred"
    else
        log_info "All files are identical - nothing was transferred"
    fi
fi

# Check rsync exit status
if [ $RSYNC_EXIT -eq 0 ] || [ $RSYNC_EXIT -eq 24 ]; then
    if [ "$DRY_RUN" = true ]; then
        log_info "Dry run completed successfully"
    else
        log_info "Sync completed successfully"
    fi
elif [ $RSYNC_EXIT -eq 23 ]; then
    log_warn "Sync completed with some vanished files (this is usually normal)"
else
    log_error "Rsync failed with exit code $RSYNC_EXIT"
    echo "Rsync output:"
    echo "$RSYNC_OUTPUT"
    exit $RSYNC_EXIT
fi

# Post-sync integrity verification: compare file sizes between server and local.
# This catches partial/truncated downloads (e.g. files still being written during sync).
INTEGRITY_ERRORS=0
if [ "$DRY_RUN" = false ]; then
    log_step "Verifying file integrity (size check)..."

    # Get file sizes from server: "size path" per line
    REMOTE_SIZES=$(ssh "$SERVER" "cd $REMOTE_DIR && find . -type f \
        ! -name '*.tmp' ! -name '*.lock' ! -name '.last_sync' ! -path './.git/*' \
        -printf '%s %p\n'" 2>/dev/null || true)

    if [ -n "$REMOTE_SIZES" ]; then
        MISMATCH_FILES=()
        while IFS= read -r line; do
            remote_size=$(echo "$line" | cut -d' ' -f1)
            rel_path=$(echo "$line" | cut -d' ' -f2-)
            local_file="$LOCAL_DIR/${rel_path#./}"

            if [ -f "$local_file" ]; then
                local_size=$(stat -c%s "$local_file" 2>/dev/null || echo "0")
                if [ "$local_size" != "$remote_size" ]; then
                    MISMATCH_FILES+=("$rel_path|$local_size|$remote_size")
                fi
            fi
        done <<< "$REMOTE_SIZES"

        if [ ${#MISMATCH_FILES[@]} -gt 0 ]; then
            INTEGRITY_ERRORS=${#MISMATCH_FILES[@]}
            log_warn "Size mismatch detected in $INTEGRITY_ERRORS file(s)! Re-downloading..."
            echo ""
            for entry in "${MISMATCH_FILES[@]}"; do
                rel_path=$(echo "$entry" | cut -d'|' -f1)
                local_sz=$(echo "$entry" | cut -d'|' -f2)
                remote_sz=$(echo "$entry" | cut -d'|' -f3)
                local_file="$LOCAL_DIR/${rel_path#./}"
                echo -e "   ${YELLOW}FIX${NC}  ${rel_path#./}  (local: ${local_sz}B, server: ${remote_sz}B)"
                # Re-download the mismatched file
                scp -q "$SERVER:$REMOTE_DIR/${rel_path#./}" "$local_file" 2>/dev/null || {
                    log_error "Failed to re-download: ${rel_path#./}"
                }
            done
            echo ""

            # Verify fixes
            STILL_BAD=0
            for entry in "${MISMATCH_FILES[@]}"; do
                rel_path=$(echo "$entry" | cut -d'|' -f1)
                remote_sz=$(echo "$entry" | cut -d'|' -f3)
                local_file="$LOCAL_DIR/${rel_path#./}"
                local_sz=$(stat -c%s "$local_file" 2>/dev/null || echo "0")
                if [ "$local_sz" != "$remote_sz" ]; then
                    STILL_BAD=$((STILL_BAD + 1))
                    log_error "Still mismatched after re-download: ${rel_path#./}"
                fi
            done

            if [ "$STILL_BAD" -eq 0 ]; then
                log_info "All $INTEGRITY_ERRORS mismatched file(s) fixed successfully"
            else
                log_error "$STILL_BAD file(s) could not be fixed"
            fi
        else
            log_info "All files verified (sizes match)"
        fi
    else
        log_warn "Could not retrieve remote file sizes for verification"
    fi
fi

# Show summary if not dry run
if [ "$DRY_RUN" = false ]; then
    echo ""
    log_step "Sync Summary"

    FILE_COUNT=$(find "$LOCAL_DIR" -type f | wc -l)
    DIR_COUNT=$(find "$LOCAL_DIR" -type d | wc -l)
    TOTAL_SIZE=$(du -sh "$LOCAL_DIR" 2>/dev/null | cut -f1)

    echo "  Directories: $DIR_COUNT"
    echo "  Files:       $FILE_COUNT"
    echo "  Total size:  $TOTAL_SIZE"
    if [ "$INTEGRITY_ERRORS" -gt 0 ]; then
        echo -e "  Integrity:   ${YELLOW}${INTEGRITY_ERRORS} file(s) were re-downloaded${NC}"
    else
        echo -e "  Integrity:   ${GREEN}all files verified${NC}"
    fi
fi

echo ""
log_info "Sync operation complete!"
