#!/bin/bash
#
# setup-openrouter.sh - Set up OpenRouter API key for the AI agent
#
# Usage: ./setup-openrouter.sh [API_KEY]
#
# If API_KEY is not provided, you'll be prompted to enter it.
#
# Get your API key from: https://openrouter.ai/keys
#

set -e

# Configuration
OPENROUTER_ENV="$HOME/.config/mini-swe-agent/.env.openrouter"
OPENROUTER_BASE_URL="https://openrouter.ai/api/v1"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}✓${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }
log_step() { echo -e "${BLUE}→${NC} $1"; }

echo ""
echo "=========================================="
echo "  OpenRouter Setup for AI Agent"
echo "=========================================="
echo ""

# Get API key
API_KEY="${1:-}"

if [ -z "$API_KEY" ]; then
    echo "Get your API key from: https://openrouter.ai/keys"
    echo ""
    read -p "Enter your OpenRouter API key: " -s API_KEY
    echo ""
fi

if [ -z "$API_KEY" ]; then
    log_error "No API key provided"
    exit 1
fi

# Validate API key format (OpenRouter keys start with sk-)
if [[ ! "$API_KEY" =~ ^sk- ]]; then
    log_warn "API key doesn't start with 'sk-' - this might not be a valid OpenRouter key"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Test the API key
log_step "Testing API key..."

# Use a free model for testing
TEST_MODEL="meta-llama/llama-3.2-3b-instruct:free"
RESPONSE=$(curl -s -w "\n%{http_code}" -m 30 -X POST "${OPENROUTER_BASE_URL}/chat/completions" \
    -H "Authorization: Bearer $API_KEY" \
    -H "Content-Type: application/json" \
    -H "HTTP-Referer: https://github.com/ai-lives-on-computer" \
    -H "X-Title: AI-Lives-On-Computer" \
    -d "{\"model\": \"$TEST_MODEL\", \"messages\": [{\"role\": \"user\", \"content\": \"Say hello in one word.\"}], \"max_tokens\": 10}" 2>/dev/null)

HTTP_CODE=$(echo "$RESPONSE" | tail -1)
BODY=$(echo "$RESPONSE" | head -n -1)

if [ "$HTTP_CODE" = "200" ]; then
    log_info "API key is valid!"
else
    log_error "API key validation failed (HTTP $HTTP_CODE)"
    echo "Response: $BODY"
    exit 1
fi

# Create config directory if needed
mkdir -p "$(dirname "$OPENROUTER_ENV")"

# Write the configuration
log_step "Writing configuration to $OPENROUTER_ENV"

cat > "$OPENROUTER_ENV" << ENVEOF
# OpenRouter Configuration for AI Agent
# Generated by setup-openrouter.sh on $(date)
#
# API Documentation: https://openrouter.ai/docs
# Available Models: https://openrouter.ai/models

OPENAI_API_KEY=$API_KEY
OPENAI_BASE_URL=$OPENROUTER_BASE_URL
MSWEA_MODEL_NAME=openai/meta-llama/llama-3.3-70b-instruct
MSWEA_CONFIGURED=true
MSWEA_COST_TRACKING=ignore_errors
ENVEOF

log_info "Configuration saved!"

# Show available free models
echo ""
echo "=========================================="
echo "  Popular Free Models on OpenRouter"
echo "=========================================="
echo ""
echo "  meta-llama/llama-3.2-3b-instruct:free     (3B, fast)"
echo "  meta-llama/llama-3.3-70b-instruct:free    (70B, capable)"
echo "  google/gemma-2-9b-it:free                 (9B, good)"
echo "  mistralai/mistral-7b-instruct:free        (7B, fast)"
echo "  qwen/qwen-2.5-72b-instruct:free           (72B, very capable)"
echo ""
echo "  See all models: https://openrouter.ai/models?q=free"
echo ""

# Show how to use
echo "=========================================="
echo "  How to Use"
echo "=========================================="
echo ""
echo "1. Set the model in ~/ai_home/config.sh:"
echo ""
echo "   # Add this line:"
echo "   OPENROUTER_MODEL=\"meta-llama/llama-3.3-70b-instruct:free\""
echo ""
echo "2. Run the agent with OpenRouter:"
echo ""
echo "   ./run_ai.sh openrouter"
echo ""
echo "3. Or update cron to use OpenRouter:"
echo ""
echo "   */15 * * * * ~/run_ai.sh openrouter >> ~/ai_home/logs/cron.log 2>&1"
echo ""
echo "=========================================="
log_info "Setup complete!"
echo "=========================================="
